# Generated by Django 5.1.3 on 2024-11-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('nombre_usuario', models.CharField(max_length=45)),
            ],
        ),
    ]
